### ISSUE TITLE
port the JS version of alphawave to python

### ISSUE THREAD

**Issue by Stevenic** [Stevenic/alphawave-py#1]
https://github.com/Stevenic/alphawave

I have a change coming first though which will save a bit of effort. I'm replacing the class that forks the conversation history with a more general memory fork class. I'll get that migrated over today. I also wouldn't worry about the agent stuff yet until I finish my implementation and get a couple of samples working.  The core client is what people are most likely to be interested in anyway.

**Comment by bdambrosio** [comment]
initial push for core alphawave done.No agents, and test coverage is limited, but OpenAIClient seems to work.
Assumes promptrixpy is in a directory inside alphawave with folder-name 'promptrix'

**Comment by bdambrosio** [comment]
more complete coverage, all tests run, including macbeth demo
