### ISSUE TITLE
Parity: I just checked in a change to the feedback the JSONResponseValidator gives for errors

### ISSUE THREAD

**Issue by Stevenic** [Stevenic/alphawave-py#2]
https://github.com/Stevenic/alphawave/commit/b829f475d21b859dee1d00b17ff6f0412a242651

I had a situation where `gpt-3.5-turbo` returned a JSON object where it had changed a string property into an array of strings. I wasn't able to fix this with the existing feedback. The issue turned out to be the passive nature of the error messages returned by the JSON schema validator.  I was returning feedback like:

```
The JSON returned had the following errors:
"instance.thoughts.plan" is not of a type(s) string

Return a JSON object that fixes these errors.
```

And the model would just kick back the same object it gave me before with the same issue. I ultimately got it to correct the error in playground by changing the feedback to this:

```
The JSON returned had errors. Apply these fixes:
convert "instance.thoughts.plan" to a string
```

By changing the feedback to be a list of instructions, the model happily corrected the mistake. So I basically went through the code for the JSON Schema Validator I'm using and generated repair instructions for every error that made sense.  Some things like `minimum`, `maximum`, `contains`, etc. I just ignored because I know the models going to suck at applying those fixes. I focused on the ones I thought it could do a good job at and for the rest I just return the more passive error message and tack a "Fix it." instruction on to the end.

**Comment by bdambrosio** [comment]
mostly copied over
